// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Session pooler (5432): `prisma migrate` / introspection use prepared statements and break on transaction pooler (6543).
  // Runtime still uses `DATABASE_URL` (6543) via `lib/prisma.ts`.
  datasource: {
    url: env("DIRECT_DATABASE_URL"),
  },
});
