// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** `prisma generate` never connects to the DB, but Prisma still loads this URL from config during install/CI. */
const PRISMA_GENERATE_PLACEHOLDER_URL = "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL ?? PRISMA_GENERATE_PLACEHOLDER_URL,
  },
});
