import type { ExportTableKey } from "./migration-types";

/** Child FK table first, then everything else. */
export const WIPE_ORDER: ExportTableKey[] = [
  "serviceItems",
  "leads",
  "adminUsers",
  "siteSettings",
  "navItems",
  "ctaButtons",
  "homeHero",
  "homeMarqueeItems",
  "homeExploreCards",
  "homeExploreSection",
  "homeWhereNext",
  "aboutHero",
  "aboutBuiltForItems",
  "aboutWhereNext",
  "servicesPage",
  "serviceSections",
  "processPage",
  "processSteps",
  "industriesPage",
  "industrySectors",
  "storyPage",
  "contactPage",
  "footerSettings",
  "footerNavItems",
];

/** Parents before children — serviceItems last (FK sectionId). */
export const INSERT_ORDER: ExportTableKey[] = [
  "leads",
  "adminUsers",
  "siteSettings",
  "navItems",
  "ctaButtons",
  "homeHero",
  "homeMarqueeItems",
  "homeExploreCards",
  "homeExploreSection",
  "homeWhereNext",
  "aboutHero",
  "aboutBuiltForItems",
  "aboutWhereNext",
  "servicesPage",
  "serviceSections",
  "processPage",
  "processSteps",
  "industriesPage",
  "industrySectors",
  "storyPage",
  "contactPage",
  "footerSettings",
  "footerNavItems",
  "serviceItems",
];
